name: Continuous Integration

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: "Continuous Integration"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Install node & npm"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install dependencies"
        run: npm ci
      - name: "Type checks"
        run: npm run typecheck
      - name: "Linting"
        run: npm run lint
      - name: "Tests"
        run: npm test
        env:
          BYTESCALE_ACCOUNT_ID: ${{ secrets.BYTESCALE_ACCOUNT_ID }}
          BYTESCALE_SECRET_API_KEY: ${{ secrets.BYTESCALE_SECRET_API_KEY }}
      - name: "Publish"
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically generated by GitHub / is not in our secrets.
          NPM_AUTH_TOKEN: ${{ secrets.BYTESCALE_NPM_AUTH_TOKEN }}
        run: |
          npm set //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
          npm run publish:executeIfReleaseCommit
      - name: "Notification on success"
        if: github.ref == 'refs/heads/main'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: deployments
          SLACK_COLOR: "#17BB5E"
          SLACK_TITLE: "Built: bytescale-javascript-sdk :rocket:"
          SLACK_FOOTER: "This package was successfully built."
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: "Notification on failure"
        if: github.ref == 'refs/heads/main' && failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: deployments
          SLACK_COLOR: "#BB1717"
          SLACK_TITLE: "Failed: bytescale-javascript-sdk :boom:"
          SLACK_FOOTER: "No packages published."
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
